### ISSUE TITLE
Alternative key bit-size

### ISSUE THREAD

**Issue by Raphael-sizzly** [alex-shekhter/apex-crypto-rsa-oaep-sha256#1]
Hi there!

Thanks a lot for your work, this really helped me with a current Salesforce project where we need exactly the RSAES-OAEP (PKCS#1 v2) encryption and decryption mechanisms.

I got everything to work using RSA keys with bit size of 2048 (just like you also implemented in your shells). However, the requirement in our project is to use an 4096 bit RSA key. I tried your Apex Class with an 4096 bit key exactly the same way as I did with the 2048 bit key but I keep getting the following error:

`FATAL_ERROR CryptoRSA_1_v2.CryptoRSA_1_v2_Exception: Decryption failed. Hashes are not equal...` 
`FATAL_ERROR Class.CryptoRSA_1_v2.extractClearText: line 197, column 1`
`FATAL_ERROR Class.CryptoRSA_1_v2.oaepDecode: line 190, column 1`
`FATAL_ERROR Class.CryptoRSA_1_v2.decrypt: line 152, column 1`

So my question is: is your class expected to work with 4096 bit keys as well? And if so, can you guess what I am doing wrong or what needs to be done differently compared to 2048 bit key?

Again, thanks a lot for making your work available!

**Comment by alex-shekhter** [comment]
Hi. It should work with 4096 keys too without any changes. Please take a look at the test class. Make sure that public/private keys are correct. You can use encrypt/decrypt shell scripts to quickly verify results. Please remember that decryption is very expensive with this release. You will hit cpu governor limit and also long running transaction limit probably
